name: Build Android (Crave)
on:
  workflow_dispatch:
    inputs:
      device:
        description: "Device:"
        required: true
        default: "eqe"
        type: choice
        options: ["eqe"]
      build:
        description: "Build Type:"
        required: true
        default: "user"
        type: choice
        options: ["user", "userdebug", "eng"]
      removals:
        description: "Folders to be removed before syncing:"
        required: false

env:
  android: "EvolutionX"
  manifest: "https://github.com/Evolution-X/manifest.git"
  branch: "bka"
  target: "evolution"

jobs:
  prepare:
    name: Start Runner
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: sudo apt update && sudo apt install -y tmux

      - name: Configure Crave
        run: |
          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash
          sudo mv crave /usr/local/bin/crave
          echo "$CRAVE_CONF" > ${HOME}/crave.conf
        env:
          CRAVE_CONF: ${{ secrets.CRAVE_CONF }}

      - name: Run crave devspace
        run: |
          crave devspace -- "echo "Looking for runner..."
          # Look for whether there's a runner folder set up
          if [ -f actions-runner/run.sh ] ; then
            echo "Runner found! Restarting it..."
          else
            echo "Error! Runner not found!"
            exit 1
          fi

          if tmux has-session -t ghactions; then
            echo "Runner is already Running"
          else
            tmux kill-session -t ghactions;
            tmux new-session -d -s ghactions
            tmux send-keys -t ghactions 'actions-runner/run.sh' Enter
            echo "Runner Started"
          fi"

  build:
    timeout-minutes: 1440
    name: Build using Crave
    runs-on: self-hosted
    needs: prepare

    steps:
      - name: Setup Project
        run: |
          echo "project=/crave-devspaces/${{ env.android }}" >> "$GITHUB_ENV"
          echo $CRAVE_CONF > $HOME/crave.conf
          crave clone create --projectID 93 ${{ env.project }} || echo "Crave clone create failed!"
        env:
          CRAVE_CONF: ${{ secrets.CRAVE_CONF }}

      - name: Setup crave.yaml
        run: |
          cat << EOF > ${{ env.project }}/.repo/manifests/crave.yaml
          LOS 22.1:
            ignoreClientHostname: true
            no-patch: true
            env:
              GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          EOF

      - name: Start compilation through Crave
        working-directory: ${{ env.project }}
        run: |
          crave run -- 'Run ID: ${{ github.run_id }}
          rm -rf vendor/private .repo/local_manifests ${{ inputs.removals }}

          repo init --depth 1 --git-lfs -u ${{ env.manifest }} -b ${{ env.branch }}
          git clone https://github.com/Z7G4N1U8/local_manifests .repo/local_manifests
          git clone https://$GH_TOKEN@github.com/Z7G4N1U8/android_vendor_private_keys vendor/private/keys
          /opt/crave/resync.sh

          source build/envsetup.sh
          breakfast ${{ inputs.device }} ${{ inputs.build }}
          cmka ${{ env.target }}
          '
        timeout-minutes: 1440

      - name: Pull ROM
        if: ${{ success() }}
        working-directory: ${{ env.project }}
        run: crave pull out/target/product/${{ inputs.device }}/{*.zip,boot.img,init_boot.img,vendor_boot.img,super_empty.img,recovery.img} -d ../builds/${{ github.run_id }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.android }}_${{ github.run_id }}
          path: /crave-devspaces/builds/${{ github.run_id }}

      - name: Execute if the job is cancelled
        if: ${{ cancelled() }}
        working-directory: ${{ env.project }}
        run: crave stop --all

      - name: Display error.log
        if: ${{ failure() }}
        working-directory: ${{ env.project }}
        run: crave pull out/error.log && cat out/error.log
